### ISSUE TITLE
Version 6.8.0.0 does not compile

### ISSUE THREAD

**Issue by michnovka** [bgrabitmap/bgracontrols#83] opened 2020-07-28 14:28 UTC
Version 6.8.0.0 Does not compile because:

```
Compile package bgracontrols 6.8: Exit code 1, Errors: 2, Hints: 6
bcbutton.pas(1238,55) Note: Call to subroutine "operator :=(const source:LongInt):Variant;" marked as inline is not inlined
bcbutton.pas(1249,72) Note: Call to subroutine "operator :=(const source:Variant):LongInt;" marked as inline is not inlined
bccombobox.pas(54,62) Hint: Parameter "Shift" not used
bccombobox.pas(65,7) Hint: Parameter "AState" not used
bccombobox.pas(83,30) Hint: Parameter "Message" not used
bccombobox.pas(86,38) Hint: Parameter "Shift" not used
bgravirtualscreen.pas(420,55) Error: Wrong number of parameters specified for call to "DrawPart"
bgragtkbitmap.pas(156,26) Error: Found declaration: DrawPart(TRect;TCanvas;LongInt;LongInt;Boolean);
```

**Comment by michnovka** [comment] 2020-07-28 15:09
The correct signature from [bgrabitmap package](https://github.com/bgrabitmap/bgrabitmap/blob/master/bgrabitmap/bgragtkbitmap.pas) is

` procedure DrawPart(ARect: TRect; ACanvas: TCanvas; x, y: integer; Opaque: boolean); override;`

**Comment by lainz** [comment] 2020-07-28 21:01
Hi, it works, I have it installed.

The version 6.8 of BGRAControls requires BGRABitmap 11.2.

**Comment by prof7bit** [comment] 2020-07-29 08:29
It still does not compile, the versions of BGRA* I get from the online package manager either don't fit together or something else is  wrong. Unfortunately I cannot tell which versions these are because the online package manager won't show the package version anywhere.

**Comment by lainz** [comment] 2020-07-29 12:56
What are the versions of Lazarus and FPC you're using?

If with online package manager it doesn't works, try downloading the .zip releases from bgrabitmap and bgracontrols repositories, extract it somewhere and open the .lpk files, bgrabitmap.lpk & bgracontrols.lpk.

**Comment by prof7bit** [comment] 2020-07-29 13:15
I am on the fixes branch, installed with fpcupdeluxe: Laz: 2.0.11, FPC: 3.2.1 on Kubuntu 20

The offending code is clearly in the BGRA packages, like shown in post in Post #1 

in bgravirtualscreen.pas(420,55) it is trying to call the DrawPart method wrong signature. Caller and Callee are both in the BGRA-Packages, so Lazarus version should not matter.

It is inside an ifdef LINUX, so the bug will only appear when compiling on Linux.

**Comment by lainz** [comment] 2020-07-29 14:07
Hi, ok, there is an ifdef in these lines, that line is for linux only, so it was important that you mention it.

On BGRABitmap there is this function:

procedure DrawPart(ARect: TRect; ACanvas: TCanvas; ATargetRect: TRect; Opaque: boolean); virtual;

Below the function you mentioned. So it's there.

**Comment by lainz** [comment] 2020-07-29 14:08
Try adding overload modifier to the function I mentioned.

**Comment by lainz** [comment] 2020-07-29 14:09
So It looks like this:

procedure DrawPart(ARect: TRect; ACanvas: TCanvas; x, y: integer; Opaque: boolean); overload virtual;
procedure DrawPart(ARect: TRect; ACanvas: TCanvas; ATargetRect: TRect; Opaque: boolean); overload virtual;

**Comment by lainz** [comment] 2020-07-29 14:18
That's actually fixed on dev-bgrabitmap branch, so try downloading the dev-bgrabitmap branch if you want, is not included in the release, was fixed on July 22 and version 11.2 is July 19.

@circular17 you can do a small release fix for Linux users?

**Comment by circular17** [comment] 2020-07-30 17:39
I checked and as far as I can see it is in the master branch and in version 11.2.

**Comment by lainz** [comment] 2020-07-31 00:31
> I checked and as far as I can see it is in the master branch and in version 11.2.

Yes it is, the problem is that's missing the override you commited recently

https://github.com/bgrabitmap/bgrabitmap/blob/master/bgrabitmap/bgragtkbitmap.pas#L37

**Comment by lainz** [comment] 2020-07-31 01:24
I mean the 'overload' keyword is missing not the method

**Comment by circular17** [comment] 2020-07-31 16:01
Ahhh I see

**Comment by lainz** [comment] 2020-07-31 22:41
Ok 👍 
I keep this issue open if anyone else can't install, until the new release, don't need to be right now, since the solution is very simple.
Do the release when you think will be ok to do it.

**Comment by circular17** [comment] 2020-08-02 08:20
Released new version
https://github.com/bgrabitmap/bgrabitmap/releases/tag/v11.2.1

**Comment by lainz** [comment] 2020-08-02 15:00
Thankyou, so it's solved.

**Closed by lainz** 2020-08-02 15:00 UTC
