### ISSUE TITLE
BGRABitmap cannot be compiled with current Laz/main after removal of deprecated LazUtf8Classes

### ISSUE THREAD

**Issue by wp-xyz** [bgrabitmap/bgracontrols#144] opened 2023-06-20 09:58 UTC
The deprecated LazUTF8Classes has been removed from Lazarus main (GitLab commit 74446557f6825c4ddadd9f6321a80147798dbf99). This unit is used here by BGRAUtf8. Therefore, compilation fails with current Laz main.

See v2.4 release notes: https://wiki.freepascal.org/Lazarus_2.4.0_release_notes#LazUTF8Classes_and_LazUTF8SysUtils_units

**Comment by lainz** [comment] 2023-06-22 00:21
Already reported here
https://github.com/bgrabitmap/bgrabitmap/issues/201

**Comment by circular17** [comment] 2023-06-25 14:43
Thanks for reporting

**Comment by circular17** [comment] 2023-06-25 14:43
Duplicate of https://github.com/bgrabitmap/bgrabitmap/issues/201

**Closed** 2023-06-25 14:43 UTC
