### ISSUE TITLE
Issue with Radial Progress Bar

### ISSUE THREAD

**Issue by JacoFourie** [bgrabitmap/bgracontrols#113] opened 2021-07-16 13:27 UTC
Hi. I am running the new version of Lazarus. 

Lazarus 2.3.0 r65462 FPC 3.2.2 arm-linux-gtk2

The progress bar is not in the center anymore.

![image](https://user-images.githubusercontent.com/17771641/125955231-dd506e3a-43cb-47fe-9f24-8142fca01088.png)

**Comment by JacoFourie** [comment] 2021-07-26 21:21
Hi. Anyone else with this issue?

**Comment by lainz** [comment] 2021-07-27 21:09
Hi, I currently use only releases of FPC and Lazarus.

**Comment by JacoFourie** [comment] 2021-08-05 21:07
> Hi, I currently use only releases of FPC and Lazarus.

Hi. Sorry what does that mean? So are you saying this version of Lazarus is not supported? Up to what version is supported?

**Comment by circular17** [comment] 2021-08-08 09:24
Hello,

I cannot reproduce the bug, though I tried on Linux amd64 with Lazarus 2.2.0RC1 and did not get any problem.

The bug may be related to the trunk branch.

fpcupdeluxe can install latest trunk version though it is experimental. I suggest you try with the regular installer on SourceForge:
https://www.lazarus-ide.org/index.php?page=downloads

**Comment by JacoFourie** [comment] 2021-08-08 13:39
OK I have now installed version Lazarus 2.2.0RC2 ra829c6f1f0 FPC 3.2.2 arm-linux-gtk2

And I have the same issue.

![image](https://user-images.githubusercontent.com/17771641/128633882-67f771c5-b20e-4feb-bf1d-4455ee68dc48.png)

**Comment by lainz** [comment] 2021-08-08 13:55
OK arm Linux. I don't have arm Linux to test.

The source code of this control is pretty simple can you take a look?

**Comment by JacoFourie** [comment] 2021-08-08 13:56
It looks like the Height value is null. If I hard code it to 100 it shows at the correct place.

**Comment by lainz** [comment] 2021-08-08 13:58
Try replacing height with clientheight or canvas. height.

**Comment by JacoFourie** [comment] 2021-08-08 14:07
OK so Height does have a value in it. I am still looking where this is coming from. I will install this version on Windows and look if I get the same issue.

**Comment by JacoFourie** [comment] 2021-08-08 14:14
Version Lazarus 2.1.0 r61697M FPC 3.3.1 arm-linux-gtk2 works fine BTW.

![image](https://user-images.githubusercontent.com/17771641/128635017-bb32e033-8e77-4559-a8ea-2d9fcab2218b.png)

**Comment by JacoFourie** [comment] 2021-08-08 14:26
I see other controls also has issues on the newer versions. Here is the analog Clock.

![image](https://user-images.githubusercontent.com/17771641/128635394-63d70e51-cc1b-4863-a65d-e8f1f71a992b.png)

It should look like this.

![image](https://user-images.githubusercontent.com/17771641/128635408-aeec6d85-8d7a-42f1-aa7c-ef8ce4cf7a8b.png)

**Comment by JacoFourie** [comment] 2021-08-08 14:55
OK so RC1 on Windows works fine also. So is this then a arm Linux issue?

![image](https://user-images.githubusercontent.com/17771641/128636344-ea7d9f08-62a0-4841-8abb-3f907c2d7460.png)

**Comment by JacoFourie** [comment] 2021-08-08 14:58
If this is a arm linux issue where do I report it?

**Comment by JacoFourie** [comment] 2021-08-08 15:20
OK so it definitely has something to do with the value y = Height / 2. If I hard code the y value in my app with 80 then all works fine on version 2.3.0 and version 2.2.0 RC 2

**Comment by JacoFourie** [comment] 2021-08-08 15:36
OK so if I use a variable of type single and round it so the divide is not an issue then it works.

If you do the calculation (Height / 2) in the pass to the arc function then it does not work

temp_height : single;
begin

  temp_height :=  round(Height / 2);


  FreeAndNil(FBitmap);
  FBitmap := TBGRABitmap.Create(Width , Height);

  FBitmap.Canvas2D.beginPath;
  //FBitmap.Canvas2D.arc(Width / 2, (Height / 2) , Height / 2.5, 0, pi * 2, False);
  FBitmap.Canvas2D.arc((Width / 2), temp_height , Height / 2.5, 0, pi * 2, False);
  FBitmap.Canvas2D.fillStyle(Color);
  FBitmap.Canvas2D.fill;

**Comment by JacoFourie** [comment] 2021-08-08 15:44
So is this a dataype issue? Is there not some setting that I need to set in the IDE for compiling?

**Comment by lainz** [comment] 2021-08-08 20:27
OK. Seems a bug in FPC.

**Comment by JacoFourie** [comment] 2021-08-08 21:03
When you say a bug in FPC is there a bug in the version of FPC I am using? Where should I ask about it?

**Comment by lainz** [comment] 2021-08-08 21:04
You must ask in the fpc bug tracker.

**Comment by JacoFourie** [comment] 2021-08-08 21:45
OK I am trying diffrent versions of FPC with Lazarus. Version 3.2.0 does the same

![image](https://user-images.githubusercontent.com/17771641/128646639-d85e5c1b-b1c7-4324-bb7d-2f97710b6a4b.png)

**Comment by JacoFourie** [comment] 2021-08-08 22:27
FPC 3.2.3 also has the issue on Arm. But on Windows it is fine. So is there an issue with FPC on Arm Linux according to you?

![image](https://user-images.githubusercontent.com/17771641/128647472-23377dcd-af97-4115-9287-01778f41abce.png)

**Comment by lainz** [comment] 2021-08-08 22:31
Yes there's a bug in arm.

If you can create a fork of the dev branch of bgracontrols and fix the
controls for arm with the intermediate calculations... Easier than waiting
fpc to fix it.

**Comment by circular17** [comment] 2021-08-08 23:00
Where to declare the bug: https://gitlab.com/freepascal.org/fpc/source/-/issues
The closest I could find, but might be different: https://gitlab.com/freepascal.org/fpc/source/-/issues/28140

It might help if you can reproduce the bug with a simple program, without any library, just with one a function with the same signature. Note that if it works in FPC 3.3.1 and not in FPC 3.2.2, it might already have been fixed in trunk.

**Comment by JacoFourie** [comment] 2021-08-08 23:15
Thanks. I am trying to install FPC 3.3.1 but the installer now has an error and bombs out. They moved all the stuff over from svn to GitLab and now TRUNK does not seem to work with Fpcupdeluxe. 

I tried to make a small program but it works in the small program.  Will update is a progress.  I dont need to have this working yet. I am just making sure stuff still works in the new version so when I do move over it still works and I do not have an issue then.

**Comment by JacoFourie** [comment] 2021-08-09 08:02
Mmmmm I am not sure what to say, I got FPC 3.3.1 working but now it even does worse.

![image](https://user-images.githubusercontent.com/17771641/128675813-b8632bbe-cd9a-4f04-a76c-f625c0da8df4.png)

**Comment by JacoFourie** [comment] 2021-08-09 12:43
So using the latest Lazarus IDE and the Latest FPC I have to replace all the calculations in the acr call. Then the control works at  run time.

`procedure TBCRadialProgressBar.RenderControl;
var
  textBmp: TBGRABitmap;
  textStr: string;
  EffectiveLineWidth:single;
  temp_height  : single;
  temp_width   : single;
  temp_height2 : single;
  temp_pi      : single;
  temp_arc     : single;

begin

  temp_height := Height;

  FreeAndNil(FBitmap);
  FBitmap := TBGRABitmap.Create(Width, Height);

  temp_width  := Width / 2;
  temp_height := Height / 2;
  temp_height2 := Height / 2.5;
  temp_pi := pi * 2;

  FBitmap.Canvas2D.beginPath;
  FBitmap.Canvas2D.arc(temp_width, temp_height, temp_height2, 0, temp_pi, False);
  FBitmap.Canvas2D.fillStyle(Color);
  FBitmap.Canvas2D.fill;

  if LineWidth=0 then
    EffectiveLineWidth:=Height / 50
  else
    EffectiveLineWidth:=LineWidth;

  FBitmap.Canvas2D.lineWidth := EffectiveLineWidth;
  FBitmap.Canvas2D.strokeStyle(LineBkgColor);
  FBitmap.Canvas2D.stroke;

  FBitmap.Canvas2D.beginPath;
  temp_pi := pi * 1.5;
  temp_arc :=  (pi * 1.5) + ((pi * 2) * Value / MaxValue);
  if Value <> MinValue then
    FBitmap.Canvas2D.arc(temp_width, temp_height, temp_height2, temp_pi, temp_arc , False);
  FBitmap.Canvas2D.fillStyle(BGRAPixelTransparent);
  FBitmap.Canvas2D.fill;

  FBitmap.Canvas2D.lineWidth := EffectiveLineWidth;
  FBitmap.Canvas2D.strokeStyle(LineColor);
  FBitmap.Canvas2D.stroke;

  if MaxValue = 0 then
    textStr := '0%'
  else
    textStr := FloatToStr((Value / MaxValue) * 100) + '%';

  textBmp := TextShadow(Width, Height, textStr, Font.Height,
    Font.Color, FontShadowColor, FontShadowOFfsetX,
    FontShadowOffsetY, FontSHadowRadius, Font.Style, Font.Name) as TBGRABitmap;
  FBitmap.PutImage(0, 0, textBmp, dmDrawWithTransparency);
  textBmp.Free;
end;`


![image](https://user-images.githubusercontent.com/17771641/128707827-00103e38-97cb-49f9-8064-93caff31e3cc.png)


But at design time in the GUI builder it is still wrong. Is the same code not called in the design time interface to create the control?

![image](https://user-images.githubusercontent.com/17771641/128707970-61e121ca-014a-48ac-81c7-eadf9693663d.png)

**Comment by JacoFourie** [comment] 2021-08-09 17:25
This is so scary. How can FPC do this?

I print the value of Height and Width before I call arc. And then again inside arc.

Before the call
`writeln('Width  : ' + floattostr(Width));
  writeln('Height : ' + floattostr(Height));

  writeln('Half Width  : ' + floattostr(Width / 2));
  writeln('Half Height : ' + floattostr(Height / 2));

//  FBitmap.Canvas2D.arc(temp_width, temp_height, temp_height2, 0, temp_pi, False);
  FBitmap.Canvas2D.arc(Width / 2, Height / 2, Height / 2.5, 0, pi * 2, False); `


and then inside the arc procedure at th start of the proc.

`procedure TBGRACanvas2D.arc(x, y, radius, startAngleRadCW, endAngleRadCW: single;
  anticlockwise: boolean);
var pts: array of TPointF;
  temp: single;
  pt: TPointF;
  rx,ry: single;
  len1,len2: single;
  unitAffine: TAffineMatrix;
  v1orig,v2orig,v1ortho,v2ortho: TPointF;
  startRadCCW,endRadCCW: single;
begin
  writeln('X in arc : ' + floattostr(x));
  writeln('Y in arc : ' + floattostr(y));
  v1orig := PointF(currentState.matrix[1,1],currentState.matrix[2,1]);
  v2orig := PointF(currentState.matrix[1,2],currentState.matrix[2,2]); `

And here is the output. This is very scary that FPC does this. Y should be 100, yet it is 3.390625

`Width  : 200
Height : 200
Half Width  : 100
Half Height : 100
X in arc : 100
Y in arc : 3.390625
`

**Comment by circular17** [comment] 2021-08-11 06:36
Hello Jaco 

To see the changes in the designer you need to recompile Lazarus. As you did when you installed BGRAControls in the first place.

About trunk I understand it is frightening. I cannot help with that, but it is common to have bugs in trunk

**Comment by JacoFourie** [comment] 2021-08-11 10:12
OK cool thanks that did the trick. I have these issues on non TRUNK versions also on ARM so it is not just on TRUNK.
But at least I now know what is the reason for it and how to get around it.

![image](https://user-images.githubusercontent.com/17771641/129011681-d4d73ebc-beb6-40f2-ae61-4803f00e3e10.png)

**Comment by circular17** [comment] 2021-08-11 17:38
Cool glad you have a solution

**Closed by circular17** 2021-08-11 17:38 UTC
