### ISSUE TITLE
TBGRASVGImageList memory leak

### ISSUE THREAD

**Issue by Lulu04** [bgrabitmap/bgracontrols#151] opened 2023-09-07 19:44 UTC
Hi, thank you for BGRAControl !
There is memory leak in TBGRASVGImageList. To reproduce, create a new project, put on the form an instance of TBGRASVGImageList, compile and run with heaptrc enabled.

Attached the report generated by heaptrc.
Regards
[HEAP.txt](https://github.com/bgrabitmap/bgracontrols/files/12552882/HEAP.txt)

**Comment by circular17** [comment] 2023-09-07 20:17
Hi Lulu!

Thanks to Lainz, BGRAControls has been continuously maintained.

About the memory leak you're mentionning, it is a known one that depends on FPC code and that has been fixed in recent versions, though this may not be in the latest stable release of Lazarus.

**Comment by circular17** [comment] 2023-09-07 20:18
Duplicate of https://github.com/bgrabitmap/bgracontrols/issues/134

**Comment by circular17** [comment] 2023-09-07 20:23
Thank you Lulu, for taking the time to report this issue! Even though this particular memory leak is known to us, we always value the contributions and vigilance. Please continue to share any other observations or suggestions you might have in the future!

**Closed** 2023-09-07 20:23 UTC

**Comment by Lulu04** [comment] 2023-09-08 09:51
Sorry, I don't look in the closed issues list before posting.
I will continue to share! Let's go! :)

**Comment by circular17** [comment] 2023-09-08 13:09
No need to apologize! Typically, users aren't expected to go through closed issues before reporting. Given that this issue pertains to FPC, it does fall into a gray area. So, don't worry too much about checking closed issues; I'm here to help identify if something's been addressed before.
